package main

import (
	"fmt"
	"math/rand"
)

// "Fun" messages that will be displayed in the footer
var funMsg = []string{
	"Web scraping is not a crime.",
	"Made in Sweden.",
	"🙃",
	"Hello.",
	"<3",
	"So many feeds, so little time.",
	"A feed in the hand is worth two in the bush.",
	"Death begets death begets death.",
	"I am Eo's dream.",
	"Through the thorns to the stars.",
	"Freedom in an unjust system is no freedom at all.",
	"Omnis vir lupus.",
	"Shit escalates.",
	"Break the chains, my love.",
	"Sharpened by hate. Strengthened by love.",
	"Hic sunt leones.",
	"The Reaper has come. And he's brought hell with him.",
	"Keyboard not found. Press F1 to continue.",
	"The stars shine brighter when shared among comrades.",
	"Zzz... 🛌",
	"Generated in 0 ms.",
	"Open source, open heart.",
	"RSS is the new black.",
	"Unsubscribe.",
	"Copyright © 2004-2021 Microsoft Corporation.",
	"ChatGPT made 99% of this website :-)",
	fmt.Sprintf("%d is the year of the Linux desktop.", 2024+rand.Intn(100)),
	":-)",
	":^)",
	"( ͡° ͜ʖ ͡°)",
	"pls seed",
	"My life for Aiur!",
	"For the swarm!",
	"Do not the cat.",
	"hal[",
	"Meow?",
	"Rawr!",
	"👁️👄👁️",
	"From each planet, to each star—equality in the cosmos.",
	"In the vastness of space, no one should own more than they can share.",
	"http://",
	"Workers of the universe, unite! The stars are our common heritage.",
	"Space is for all, not just the privileged few.",
	"No more celestial landlords!",
	"From the red planet to the black hole, solidarity knows no borders.",
	"Astronauts of the world, unite for a cosmic revolution!",
	"Space is for everyone, not just the 1%.",
	"No class struggle in zero gravity.",
	"Only solidarity among the cosmic proletariat.",
	"The red glow of the stars reflects the spirit of collective effort.",
	"The final frontier is a shared frontier, where no one is left behind.",
	"Vote for a space utopia!",
	"Space is for the many, not the few.",
	"From the Milky Way to Andromeda, the stars belong to the people.",
	"Space is for the workers, not the bosses.",
	"Let the fruits of progress be the common heritage of all.",
	"From the moon to the asteroid belt, the cosmos is for the common good.",
	"The stars do not discriminate; neither should we.",
	"In the vacuum of space, let equality fill the void.",
	"From Big Bang to the heat death of the universe, solidarity is eternal.",
	"Your body betrays your degeneracy.",
	"You need to get your shit together.",
	"I can't help you. I am totally useless.",
	"In dark times, should the stars also go out?",
	"One day I will return to your side.",
	"Un Jour Je Serai de Retour Prés de Toi",
	"These communists aren't men, they're *mole people*!",
	"You should build Communism — precisely *because* it's impossible.",
	"She thinks you are an idiot, sire.",
	"The song of death is sweet and endless.",
	"Child-murdering billionaires still rule the world with a shit-eating grin.",
	"Instead of building Communism, he now builds grotesque sites.",
	"Eight billion people - and you failed every single one of them.",
	"You are the first crack. From you it will spread.",
	"Playing Sad F.M.",
	"Do you remember the scent of your childhood?",
	"You are a man with a lot of past, little present and almost no future.",
	"European utopia or death",
	"What do the know about Sweden, who only Sweden know?",
	"Imagine a life in which all your basic needs were met.",
}
