# Generated by Django 5.0.3 on 2024-03-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedvault', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
