# Generated by Django 5.0.3 on 2024-03-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedvault', '0003_rename__id_entry_entry_id_rename__id_feed_feed_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='bozo',
            field=models.BooleanField(default=False),
        ),
    ]
