# Generated by Django 5.0.3 on 2024-03-17 03:29

import feedvault.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedvault', '0005_useruploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruploadedfile',
            name='original_filename',
            field=models.TextField(default='a', help_text='The original filename of the file.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useruploadedfile',
            name='file',
            field=models.FileField(upload_to=feedvault.models.get_upload_path),
        ),
    ]
