# Generated by Django 5.0.3 on 2024-03-17 16:00

import django.db.models.deletion
import feedvault.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedvault', '0006_useruploadedfile_original_filename_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useruploadedfile',
            name='description',
            field=models.TextField(blank=True, help_text='Description added by user.'),
        ),
        migrations.AddField(
            model_name='useruploadedfile',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes from admin.'),
        ),
        migrations.AlterField(
            model_name='useruploadedfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The time the file was uploaded.'),
        ),
        migrations.AlterField(
            model_name='useruploadedfile',
            name='file',
            field=models.FileField(help_text='The file that was uploaded.', upload_to=feedvault.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='useruploadedfile',
            name='has_been_processed',
            field=models.BooleanField(default=False, help_text='Has the file content been added to the archive?'),
        ),
        migrations.AlterField(
            model_name='useruploadedfile',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='The last time the file was modified.'),
        ),
        migrations.AlterField(
            model_name='useruploadedfile',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user that uploaded the file.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
