# Generated by Django 5.0.2 on 2024-02-23 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name'], 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ['name'], 'verbose_name': 'Domain', 'verbose_name_plural': 'Domains'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created_parsed'], 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['-created_at'], 'verbose_name': 'Feed', 'verbose_name_plural': 'Feeds'},
        ),
        migrations.AlterModelOptions(
            name='generator',
            options={'ordering': ['name'], 'verbose_name': 'Feed generator', 'verbose_name_plural': 'Feed generators'},
        ),
        migrations.AlterModelOptions(
            name='links',
            options={'ordering': ['href'], 'verbose_name': 'Link', 'verbose_name_plural': 'Links'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['name'], 'verbose_name': 'Publisher', 'verbose_name_plural': 'Publishers'},
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('name', 'email', 'href')},
        ),
        migrations.AlterUniqueTogether(
            name='links',
            unique_together={('href', 'rel')},
        ),
        migrations.AlterUniqueTogether(
            name='publisher',
            unique_together={('name', 'email', 'href')},
        ),
    ]
