# Generated by Django 5.0.1 on 2024-01-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The URL to block.', unique=True)),
            ],
            options={
                'verbose_name': 'Blocklist',
                'verbose_name_plural': 'Blocklists',
                'db_table_comment': 'A list of URLs to block.',
            },
        ),
    ]
