// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CountFeeds(ctx context.Context) (int64, error)
	CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error)
}

var _ Querier = (*Queries)(nil)
