// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: stats.sql

package db

import (
	"context"
)

const dBSize = `-- name: DBSize :one
SELECT pg_size_pretty(pg_database_size(current_database()))
`

func (q *Queries) DBSize(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, dBSize)
	var pg_size_pretty string
	err := row.Scan(&pg_size_pretty)
	return pg_size_pretty, err
}
